title: 'folow - minimalistic blog'
name: 'folow'
description: 'Description of main page'
theme_color: '#202225'
image_home: img/folow.jpg
url: 'https://apexof.github.io'
baseurl: '/'
github_username: 'apexof'
plugins: [jekyll-paginate-v2]
category_dir: 'blog'
pagination:
  enabled: true
  per_page: 9
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
exclude: [
  'node_modules', 
  'gulpfile.js', 
  'package.json', 
  'package-lock.json', 
  'npm-debug.log', 
  '**/Thumbs.db', 
  'libs', 
  'css',
  'sass',
  'images',
  'js'
]
keep_files: [
  'css',
  'js',
  'images',
]
soc:
  <ul>
    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
    <li><a href="#"><i class="fas fa-rss"></i></a></li>	
  </ul>	
copyright: 'All rights reserved'
icons:
  other: '<i class="fas fa-box-open"></i>'
  philosophy: '<i class="fas fa-yin-yang"></i>'
  games: '<i class="fas fa-gamepad"></i>'
  sport: '<i class="fas fa-football-ball"></i>'
  music: '<i class="fas fa-headphones"></i>'
  it-news: '<i class="fas fa-desktop"></i>'
  travels: '<i class="fas fa-plane"></i>'
  animals: '<i class="fas fa-paw"></i>'
  food: '<i class="fas fa-utensils"></i>'
            